name: build_and_test

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.4"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2
      - name: Install pkg-config via brew
        run: brew install pkg-config
      - name: Install openssl via brew
        run: brew install openssl
      - name: Install unbound via brew
        run: brew install unbound
      - name: show pkg-config search path
        run: pkg-config --variable pc_path pkg-config
      - name: show include path for libunbound
        run: pkg-config --cflags libunbound
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test