name: build_and_test

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5"]
    runs-on: ${{ matrix.os }}
    env:
      PKG_CONFIG_PATH: "/usr/local/opt/openssl@3/lib/pkgconfig"
      LIBRARY_PATH: "/home/linuxbrew/.linuxbrew/Cellar/unbound/1.13.2_1/lib/"
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2
      - name: Install pkg-config via brew
        run: brew install pkg-config
      - name: Install openssl via brew
        run: brew install openssl
      - name: Install unbound via brew
        run: brew install unbound
      - name: show pkg-config search path
        run: pkg-config --variable pc_path pkg-config
      - name: show include path for libunbound
        run: pkg-config --cflags libunbound && pkg-config --libs libunbound  
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test